version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started on $(date)"
 pre_build:
    commands:
      - echo Logging in to Docker Hub...
      # Type the command to log in to your Docker Hub account here.          
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t helloworld .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker images
      - echo Running the Docker image...
      - docker run helloworld
